# Generated by Django 2.1.5 on 2019-09-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
