# Generated by Django 2.1.5 on 2019-09-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='user_id',
        ),
    ]
